### ISSUE TITLE
[Bug] 1.19.2 getScreenHelper throws UnsupportedOperationException

### ISSUE THREAD

**Issue by tatoyoda600** [shedaniel/REIPluginCompatibilities-Issues#58]
### What happened?

On 1.19.2, the game crashes whenever REI's `getScreenHelper` function is called, as it's not implemented.
In my case EMI tries calling it when I open my inventory.
If I use Jade's keybinds to access a recipe/usage screen directly without opening my inventory, then I can use the REI UI without issues, since on that screen EMI isn't active and thus the function isn't called.

### Relevant log output

```shell
-- Head --
Thread: Render thread
Suspected Mods: 
	EMI (emi), Version: 1.1.6+1.19.2+forge
		at TRANSFORMER/emi@1.1.6+1.19.2+forge/dev.emi.emi.jemi.JemiPlugin.lambda$register$4(JemiPlugin.java:167)

	REI Plugin Compatibilities (rei_plugin_compatibilities), Version: 9.0.90
		Issue tracker URL: https://github.com/shedaniel/RoughlyEnoughItems/issues
		at TRANSFORMER/rei_plugin_compatibilities@9.0.90/me.shedaniel.rei.jeicompat.JEIPluginDetector.TODO(JEIPluginDetector.java:123)
Stacktrace:
	at me.shedaniel.rei.jeicompat.JEIPluginDetector.TODO(JEIPluginDetector.java:123) ~[REIPluginCompatibilities-forge-9.0.90.jar%23454!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at me.shedaniel.rei.jeicompat.wrap.JEIJeiRuntime.getScreenHelper(JEIJeiRuntime.java:47) ~[REIPluginCompatibilities-forge-9.0.90.jar%23454!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dev.emi.emi.jemi.JemiPlugin.lambda$register$4(JemiPlugin.java:167) ~[emi-1.1.6+1.19.2+forge.jar%23388!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dev.emi.emi.registry.EmiStackProviders.getStackAt(EmiStackProviders.java:47) ~[emi-1.1.6+1.19.2+forge.jar%23388!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at dev.emi.emi.screen.EmiScreenManager.getHoveredStack(EmiScreenManager.java:515) ~[emi-1.1.6+1.19.2+forge.jar%23388!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at dev.emi.emi.screen.EmiScreenManager.getHoveredStack(EmiScreenManager.java:507) ~[emi-1.1.6+1.19.2+forge.jar%23388!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at dev.emi.emi.screen.EmiScreenManager.renderCurrentTooltip(EmiScreenManager.java:733) ~[emi-1.1.6+1.19.2+forge.jar%23388!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at dev.emi.emi.screen.EmiScreenManager.drawForeground(EmiScreenManager.java:644) ~[emi-1.1.6+1.19.2+forge.jar%23388!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B}
	at dev.emi.emi.platform.forge.EmiClientForge.postRenderScreen(EmiClientForge.java:100) ~[emi-1.1.6+1.19.2+forge.jar%23388!/:?] {re:classloading,pl:rei_plugin_compatibilities:B}
	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:260) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:252) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%2385!/:?] {}
	at net.minecraftforge.client.ForgeHooksClient.drawScreenInternal(ForgeHooksClient.java:442) ~[forge-1.19.2-43.4.0-universal.jar%23492!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A}
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:434) ~[forge-1.19.2-43.4.0-universal.jar%23492!/:?] {re:mixin,re:classloading,pl:rei_plugin_compatibilities:B,pl:mixin:A}
-- Screen render details --
Details:
	Screen name: net.minecraft.client.gui.screens.inventory.CreativeModeInventoryScreen
	Mouse location: Scaled: (480, 254). Absolute: (960.000000, 508.000000)
	Screen size: Scaled: (960, 509). Absolute: (1920, 1017). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:896) ~[client-1.19.2-20220805.130853-srg.jar%23487!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23487!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23487!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:rei_plugin_compatibilities:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23487!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23487!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.4.0.jar%23101!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2388!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}
```

### Anything else?

The specific EMI code line from the stacktrace: https://github.com/emilyploszaj/emi/blob/1.19.2/xplat/src/main/java/dev/emi/emi/jemi/JemiPlugin.java#L167

The JEI code line it's expecting:
https://github.com/mezz/JustEnoughItems/blob/1.19/Library/src/main/java/mezz/jei/library/runtime/JeiRuntime.java#L122

The REIPluginCompatibilities line according to the stacktrace:
`me.shedaniel.rei.jeicompat.wrap.JEIJeiRuntime.getScreenHelper(JEIJeiRuntime.java:47)`

### By submitting this issue, I have included the necessary logs by pasting the contents into the correct location or attaching the file as an upload.

- [X] Yes, and I did not use any paste services other than GitHub Gists.

### By submitting this issue, I have confirmed my REI and REI's dependencies are up to date.

- [X] Yes

**Comment by shedaniel** [comment]
REIPC isn’t compatible with EMI, it does not implement the necessary apis that EMI uses to takeover JEI, and also doesn’t re-wrap REI code as JEI api that well (most of the work is done on adapting JEI to REI, not the reverse, it is a stub)
